move_group:
  arm:
    # Velocity and acceleration scaling for manipulator planning in MoveIt
    planning_time: 50
    planning_attempts: 5
    velocity_scaling: 0.2
    acceleration_scaling: 0.99

    left: [0.791303, -0.109673, -1.007676, -2.054506, 1.608512, 2.168921, -1.934002]
    right: [-0.849273, -0.996814, 1.041194, -2.477326, 1.713547, 2.817316, -1.667401]
    home: [-0.204593, -0.399106, 0.192406, -1.812055, 0.023015, 1.606686, -0.032432]

  panda_arm:
    # Velocity and acceleration scaling for manipulator pla nning in MoveIt
    planning_time: 50
    planning_attempts: 5
    velocity_scaling: 0.2
    acceleration_scaling: 0.99

    # Home joint positions for the panda robot
    # home: [0.0, -0.785, 0.0, -2.356, 0.0, 1.571, 0.785]
    home: [-0.204593, -0.399106, 0.192406, -1.812055, 0.023015, 1.606686, -0.032432]

  hand:
    planning_time: 50
    planning_attempts: 5
    velocity_scaling: 0.2
    acceleration_scaling: 0.99

    # Home joint positions for the panda robot
    home: [0.0]

  gripper:
    planning_time: 50
    planning_attempts: 5
    velocity_scaling: 0.2
    acceleration_scaling: 0.99

    # Home joint positions for the panda robot
    home: [0.04]