  controller_manager_ns: ''
  controller_list:
    - name: effort_joint_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7


      # control the qbhand motors and its relative synergy
    - name:  qbhand2m1/control/qbhand2m1_synergies_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      joints:
        - qbhand2m1_synergy_joint
        - qbhand2m1_manipulation_joint 



    #   # control the qbhand 2 with motor positions
    # - name:  qbhand2m1_motor_positions_trajectory_controller
    #   action_ns: follow_joint_trajectory
    #   type: FollowJointTrajectory
    #   joints:
    #     - qbhand2m1_motor_1_joint
    #     - qbhand2m1_motor_2_joint