  controller_manager_ns: ''
  controller_list:
    - name: effort_joint_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

# control the qbhand motors and its relative synergy
qbhand2m1_synergies_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - qbhand2m1_synergy_joint
    - qbhand2m1_manipulation_joint
  constraints:  # fake values due to the adaptability
    goal_time: 10.0
    stopped_velocity_tolerance: 10.0
    qbhand2m1_synergy_joint:
      trajectory: 10.0
      goal: 10.0
    qbhand2m1_manipulation_joint:
      trajectory: 10.0
      goal: 10.0
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbhand 2 with motor positions
qbhand2m1_motor_positions_trajectory_controller:
 type: position_controllers/JointTrajectoryController
 joints:
   - qbhand2m1_motor_1_joint
   - qbhand2m1_motor_2_joint
 constraints:  # fake values due to the adaptability
   goal_time: 10.0
   stopped_velocity_tolerance: 10.0
   qbhand2m1_motor_1_joint:
     trajectory: 10.0
     goal: 10.0
   qbhand2m1_motor_2_joint:
     trajectory: 10.0
     goal: 10.0
 state_publish_rate: 100
 action_monitor_rate: 120
 stop_trajectory_duration: 0